In [2]:
#numpy indexing and selection
import numpy as np
a=np.arange(4,41,4)
a

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [3]:
#bracket index 
a[5]

24

In [4]:
a[:5]  #uptonindex 5

array([ 4,  8, 12, 16, 20])

In [5]:
a[-1]

40

In [31]:
#broadcasting
aa=a[:5]=100 # upto inddx 5 elements will change to 100

In [32]:
aa

100

In [33]:
a

array([100, 100, 100, 100, 100,  24,  28,  32,  36,  40])

In [23]:
b=np.arange(1,11)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
 #slicing  a array
bb=b[3:6]
bb

array([4, 5, 6])

In [26]:
bb[:]=-69
bb

array([-69, -69, -69])

In [27]:
b #changes made in indexing of array also implement in original array

array([  1,   2,   3, -69, -69, -69,   7,   8,   9,  10])

In [28]:
#array copy
copy=a.copy()

In [29]:
copy

array([100, 100, 100, 100, 100,  24,  28,  32,  36,  40])

In [34]:
copy[0:5]=67
copy

array([67, 67, 67, 67, 67, 24, 28, 32, 36, 40])

In [35]:
a #changes made in the copied array wont affect orginal array

array([100, 100, 100, 100, 100,  24,  28,  32,  36,  40])

In [41]:
#indexing 2d array
d2=np.array([[5,10,15],[20,25,30],[35,40,45],[1,2,3]]) #super list each list considered as each row
d2

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [ 1,  2,  3]])

In [42]:
d2[2]

array([35, 40, 45])

In [43]:
d2[:,2]

array([15, 30, 45,  3])

In [44]:
d2[:] #   : means all rows

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [ 1,  2,  3]])

In [45]:
d2.T  # transpose

array([[ 5, 20, 35,  1],
       [10, 25, 40,  2],
       [15, 30, 45,  3]])

In [49]:
d2[0][2]

15

In [53]:
d2[3][2]

3

In [54]:
d2[2:,1:]

array([[40, 45],
       [ 2,  3]])

In [55]:
d2.shape

(4, 3)

In [56]:
#conditional sekection
c=np.arange(1,11)
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
d=c>4  # bool array
d

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [59]:
c[d]

array([ 5,  6,  7,  8,  9, 10])

In [60]:
len(c[d])

6

In [61]:
c[c>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [63]:

c[c%2==0]

array([ 2,  4,  6,  8, 10])

In [64]:
x=1
c[c%x==0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
#numpy operators
e=np.arange(0,10)

In [71]:
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
e+e

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [73]:
e-e

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [74]:
e/e

<ipython-input-74-141e7b482fd5>:1: RuntimeWarning: invalid value encountered in true_divide
  e/e


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [75]:
1/e

<ipython-input-75-28184a5244a8>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/e


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [76]:
e**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [77]:
#universal array functions
np.sqrt(e)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [78]:
np.exp(e) #exponent

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [79]:
np.power(e,1/3) # cube root

array([0.        , 1.        , 1.25992105, 1.44224957, 1.58740105,
       1.70997595, 1.81712059, 1.91293118, 2.        , 2.08008382])

In [80]:
np.max(e)

9

In [81]:
np.argmax(e)

9

In [82]:
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
np.min(e)

0

In [85]:
np.argmin(e)

0

In [87]:
np.log(e)

<ipython-input-87-c27605f42df2>:1: RuntimeWarning: divide by zero encountered in log
  np.log(e)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])