In [6]:
import numpy as np
dis=[10,15,17,26]
time=[.30,.47,.55,1.20]
ndis=np.array(dis)
ntime=np.array(time)
speed=ndis/ntime

In [7]:
speed

array([33.33333333, 31.91489362, 30.90909091, 21.66666667])

In [9]:
ndis.ndim

1

In [10]:
ndis.shape

(4,)

In [11]:
ndis.size #how many cells in a array (rows * columns)

4

In [12]:
ndis.dtype

dtype('int32')

In [16]:
matrix=[[1,2,3],[4,5,6],[7,8,9]]
matrix
m=np.array(matrix)
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
dis=[5,10,21,42]
time=[0.5,1.1,2.5,5.8]
ndis=np.array(dis)
ntime=np.array(time)
speed=ndis/ntime

In [15]:
speed

array([10.        ,  9.09090909,  8.4       ,  7.24137931])

In [18]:
new=np.arange(1,10).reshape(3,3)

In [19]:
new

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
m*new

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [21]:
new.T #transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [22]:
m,new

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [23]:
#built in methods
np.arange(0,30,3).reshape(2,5) #2 rows 5 columns

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27]])

In [24]:
np.arange(7,71,7) #  1.start ,2.stop,3.step values

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

In [29]:
z=np.zeros(9)
z.reshape(3,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
z=np.zeros((3,3,3,3))
z

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [38]:
np.eye(12) #eye makes the diagnoal value

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [40]:
#linespace
np.linspace(1,21,10)  #start value is 1 stop value is 21 in between we seperate 10 parts(values)

array([ 1.        ,  3.22222222,  5.44444444,  7.66666667,  9.88888889,
       12.11111111, 14.33333333, 16.55555556, 18.77777778, 21.        ])

In [48]:
#random
np.random.rand(5,5)*100

array([[ 3.41749644,  7.45605166, 42.35436849, 42.7921984 , 40.97351159],
       [85.17834847, 91.40258239,  7.38233089, 87.1526115 , 30.45047109],
       [ 3.23071605, 94.12746447,  5.03236407, 26.38581369, 31.5491613 ],
       [95.22943824,  6.19723649, 35.31547261, 45.18134721, 32.129782  ],
       [25.52983126, 74.25421993, 78.06837895, 74.34689705,  6.00988094]])

In [51]:
import math
a=math.floor(np.random.rand()*100.1)
b=int(np.random.rand()*100.1)
a,b


(82, 80)

In [53]:
#rand
np.random.rand() # never give the result as 1

0.8672196312903819

In [55]:
#randn
np.random.randn(10,5) #-3 to +3 is the range 10, 5 is row and column

array([[-0.68901091,  0.74818955,  0.53809465, -1.32843254, -0.81727889],
       [ 1.54168525,  0.40343791,  0.04158539,  0.01749523, -0.89471757],
       [ 0.61328066, -0.05000382, -0.85419296, -1.70247321,  3.14313184],
       [-0.88882406,  0.09181452, -1.46381355,  0.32934298,  0.42425571],
       [-0.94403445, -0.05699763,  1.12445966, -2.15960456, -1.41939567],
       [ 0.14252401, -0.71039162,  0.42988086,  1.01612527,  0.5337355 ],
       [ 1.59355172, -0.55042563, -1.0154171 ,  0.70378078,  0.52672476],
       [-0.31962245, -0.01828259,  0.26627369,  1.0661089 , -0.45896775],
       [-0.62457603, -1.18754308,  0.73462047,  0.87492315,  0.51195992],
       [-0.03783541,  1.61625433,  0.46721606, -0.98024507, -1.4090443 ]])

In [62]:
#randint
np.random.randint(101) # any number come upto 100 not 101 

88

In [63]:
np.random.randint(0,101,25).reshape(5,5) #start value 0 stop value 101 and we divide into 25 parts

array([[98, 27, 26,  5, 82],
       [24, 68, 20, 96,  1],
       [87, 43, 93, 46, 86],
       [ 8, 26, 13, 90, 35],
       [22,  8, 61, 93, 15]])

In [65]:
#array attributes and methods
arr=np.arange(20)
rar=np.random.randint(0,10,10)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [66]:
rar

array([4, 4, 4, 2, 2, 0, 2, 8, 7, 1])

In [67]:
rar.shape

(10,)

In [68]:
#max,min,argmax,argmin
rar

array([4, 4, 4, 2, 2, 0, 2, 8, 7, 1])

In [69]:
rar.max()

8

In [70]:
rar.argmax() # gives the index 

7

In [71]:
rar.min()

0

In [72]:
rar.argmin()

5